
(function($){jQuery.jet.env.packager.domains_www_commentcamarche_net={"host":"estatic.ccmbg.com","template":"//${host}/www.commentcamarche.net/${type}/${packageName}?v=${timestamp}","timestamps":{"css":{"legacy":20170601160038,"main":20170621113337,"responsive":20170621113337,"ccm_external":20170621113339,"ckeditor":20170621113340,"ccm_newpost":20170621113340,"carrefour":20150914115015,"cisco":20150914115015,"eni":20150914115015,"exprimezvostalents":20150914115015,"info_marques":20150914115015,"kobold":20150914115015,"noel":20151127145723,"brother":20150914115015,"bobo":20150914115014,"panasonic":20150914115015,"canalplus":20160203175221},"js":{"main":20170620112717,"skin":20170601101100,"widget.forum.question":20170518095605,"ckeditor":20170612112050,"responsive":20170411112749,"navarticles":20150914115015,"bottom":20170620112717,"ga_polyfill":20170518095605,"start":20161219094535,"params.ccm.de":20170411140946,"params.ccm.en":20170411140946,"params.ccm.es":20170411140946,"params.ccm.hi":20170411140946,"params.ccm.id":20170411140946,"params.ccm.it":20170411140946,"params.ccm.nl":20170411140946,"params.ccm.pl":20170411140946,"params.ccm.pt":20170411140946,"params.ccm.ru":20170515151920,"params.df.de":20170411140946,"params.ms.de":20170411140946,"params.ms.en":20170411140946,"params.ms.es":20170411140946,"params.ms.pt":20170411140946,"params.jdf.fr":20161124152834,"params.jdf":20161124152834,"app.bottom":20170621113340,"download":20150914115015,"register":20170612142312,"profile":20170620112717,"livre":20150914115015,"advertisement.js":20150914115015,"jquery.form":20161230112122,"jquery.tablesorter":20150914115015,"jquery.sudoslider":20170329150214,"jquery.pinify":20150914115015,"jquery.dialogtarget":20150914115015,"ccm.pinify.fr":20170619103704,"ccm.pinify.it":20170619103704,"kobold":20150914115015,"eni":20150914115015,"brother":20150914115015,"canalplus":20170518095605,"carrefour":20170518095605,"carrefouradmin":20160314104347,"nativeAds":20160314151545,"figMedia.event":20170224101452,"figMedia.util":20170227104602,"figMedia.inView":20161116150103}}};}(jQuery));var $j=jQuery;ccmb={user:{},modules:{},msgs:{},lang:$data['lang'],strings:{},_io:{}};ccmb.core={_cb_handlers:[],_anim_duration:100,_login_modal_loaded:false,_timer:0,_device_ratio:null,_viewport_width:null,init:function(){$j(document).ready(function(){$ec.odr();});},odr:function(){typeof devicePixelRatio=='undefined'&&(devicePixelRatio=1);typeof navigator=='undefined'&&(navigator={});navigator.viewport=(function(){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
return{width:e[a+'Width'],height:e[a+'Height']};}());$ec._viewport_width=navigator.viewport.width;$ec._device_ratio=devicePixelRatio;if(document.getElementById('gotop')){$j(window).scroll(this.on_scroll);var t=$j(window).scrollTop();if(t>=100){$ec._gtv=true;$j('#gotop').show();}}
if(!(navigator.viewport.width>800&&devicePixelRatio==1)){$j('#gonext').hide();$j('#goprev').hide();}
if(window.location.hash){var _h=window.location.hash.match(/k\=([a-z0-9]+)/);_h&&_h[1]&&$j('div.section#'+_h[1]).hide();}},show_error:function(msg,close_cross){var c=typeof(close_cross)!='undefined'?close_cross:true;$j('#mainmsg').html('<p>'+msg+((c)?$e.msgs[$e.lang].close_cross:'')+'</p>').addClass('error').show();},show_msg:function(msg){$j('#mainmsg').html('<p>'+msg+$e.msgs[$e.lang].close_cross+'</p>').removeClass('error').slideDown(100);},hide_msg:function(){$j('#mainmsg').slideUp($ec._anim_duration);},on_click:function(event){var $this=$j(this),aid=$this.attr('actid'),aide=['tt'];if(!aid||$j.inArray(aid,aide)>-1){return true;}
var _ret=false,tgt,url;switch(aid){case'auto':case'auto append':case'auto prepend':url=$this.attr('href');tgt=$this.attr('acttgt');tgt=(tgt)?$j(tgt):null;var off=aid.indexOf(" "),man=(off>=0)?aid.slice(off+1,aid.length):'';if(url&&tgt){tgt.ajaxUpdate(url,'xhr',{manip:man,error:$ec.show_error});}
break;case'hide_msg':$ec.hide_msg();break;case'login':$j('#divModal').fadeIn(150);$j('#txtMail').focus();break;case'closeModal':$j('#divModal').fadeOut(150);break;case'follow':var size="big";if(typeof($this.attr('bsize'))!="undefined"){size="small";}
$ec.start_action($this.attr('action'),$this.attr('follow_id'),$this.attr('id'),size);event.stopPropagation();break;default:if($ec._cb_handlers['click']){for(var key in $ec._cb_handlers['click']){_ret=$ec._cb_handlers['click'][key].handler.call($this,event,aid,$ec._cb_handlers['click'][key].data);}
$j.debug(_ret);}else{_ret=true;}}
if(!_ret){event.preventDefault();}
return _ret;},on_scroll:function(event){clearTimeout(ccmb.core.on_scroll.last);ccmb.core.on_scroll.last=setTimeout(function(){var t=$j(window).scrollTop();if(!$ec._gtv&&t>=100){$ec._gtv=true;$j('#gotop').fadeIn();}
else if($ec._gtv&&t<100){$ec._gtv=false;$j('#gotop').hide();}
if(t>0){if($j('#jOICAgree')){$j('#jOICAgree').click();}}
if(!($ec._viewport_width>800&&$ec._device_ratio==1)){clearTimeout($ec._timer);$ec._timer=setTimeout(function(){$j('#gotop').hide();$ec._gtv=false;},2000);}},200);},on:function(eventType,handler,data){eventType=eventType||'click';if($j.isFunction(handler)){this._cb_handlers[eventType]=this._cb_handlers[eventType]||[];return(this._cb_handlers[eventType].push({handler:handler,data:data})-1);}
return false;},off:function(eventType,id){if(typeof(this._cb_handlers[eventType])!='undefined'&&typeof(this._cb_handlers[eventType][id])!='undefined'){return delete(this._cb_handlers[eventType][id]);}
return false;},msg:function(name,data)
{if(!data)return $e.msgs[$e.lang][name];return $e.msgs[$e.lang][name].replace(/\${([^}]+)}/igm,function(r,a){return(typeof(data[a])=='undefined'?'':data[a]);});}};$e=ccmb;$ec=$e.core;$em=$e.modules;$ec.init();var _eStat_Whap_loaded=0;if(!($ccmprms&&$ccmprms.app&&($ccmprms.app.is_portable===true))){document.write(unescape("%3Cscript src='"+location.protocol+"//w.estat.com/js/whap.js' type='text/javascript'%3E%3C/script%3E"));}
var check=function(){if(!_eStat_Whap_loaded){setTimeout(check,200);}
else{eStatWhap.serial("800000206960");eStatWhap.send();}};check();(function()
{if(!document.getElementsByClassName){var _MS_HTML5_getElementsByClassName=function(classList)
{var tokens=classList.split(" ");var staticNodeList=this.querySelectorAll("."+tokens[0]);for(var i=1;i<tokens.length;i++)
{var tempList=this.querySelectorAll("."+tokens[i]);var resultList=new Array();for(var finalIter=0;finalIter<staticNodeList.length;finalIter++)
{var found=false;for(var tempIter=0;tempIter<tempList.length;tempIter++)
{if(staticNodeList[finalIter]==tempList[tempIter])
{found=true;break;}}
if(found)
{resultList.push(staticNodeList[finalIter]);}}
staticNodeList=resultList;}
return staticNodeList;};typeof HTMLDocument!='undefined'&&(HTMLDocument.prototype.getElementsByClassName=_MS_HTML5_getElementsByClassName);typeof Element!='undefined'&&(Element.prototype.getElementsByClassName=_MS_HTML5_getElementsByClassName);}
var players=document.getElementsByClassName('jccmPlayer');if(players[0]!=undefined&&((/&ap=2/.test(players[0].src))||(!(/&ap=0/.test(players[0].src))&&!(/&ap=1/.test(players[0].src)))))
{(function(node)
{var bind=function(node,evt,fn)
{if(node.addEventListener){node.addEventListener(evt,fn,false);}
else if(node.attachEvent){node.attachEvent("on"+evt,fn);}},getTop=function(){var curtop=node.offsetTop||0,obj=node;while(obj=obj.offsetParent){curtop+=obj.offsetTop;}
return curtop;},getScrollTop=function(){return window.pageYOffset||document.documentElement.scrollTop;},getHeight=function()
{return(typeof innerHeight=='number'?innerHeight:(document.compatMode=="CSS1Compat"?document.documentElement.clientHeight:document.body.clientHeight));},endCheckNode=false,checkNodePos=function()
{if(!endCheckNode&&getTop()+(node.offsetHeight/2)<getHeight()+getScrollTop())
{node.src=node.src+'#playVideo';endCheckNode=true;}},eventTimer=0;checkNodePos();bind(window,'resize',function()
{clearTimeout(eventTimer);eventTimer=setTimeout(checkNodePos,25);});bind(window,'scroll',function()
{clearTimeout(eventTimer);eventTimer=setTimeout(function(){checkNodePos();},25);});})(players[0]);}})();$j(document).ready(function(){$j("#display1 li h2").each(function(){var h=$j(this).height();$j(this).parent().next().css("marginTop",h+2);});});ccmb.modules.navarticles={_elts:{gonext:$j('#gonext'),goprev:$j('#goprev'),gonextL:$j('#gonext .goLogo'),gonextT:$j('#gonext .goTxt'),goprevL:$j('#goprev .goLogo'),goprevT:$j('#goprev .goTxt')},init:function(){$j(document).ready(this.odr());},odr:function(){var $t=ccmb.modules.navarticles;$j('#gonext a').hover(function(){$t._show('gonext');},function(){$t._hide('gonext');});$j('#goprev a').hover(function(){$t._show('goprev');},function(){$t._hide('goprev');});var _M=window.document.URL.match(/#(goprev|gonext)$/);(_M)&&$t._show(_M[1],3000);},_show:function(which,timeout){timeout=timeout||0;var _rev=(which=='gonext')?'goprev':'gonext';this._elts[_rev+'T'].stop(true,true);this._hide(_rev);this._elts[which].width(380);this._elts[which+'L'].css({backgroundColor:"white"}).addClass("hover").animate({opacity:'0.8'},50);this._elts[which+'T'].show().animate({width:'280px'},100);if(timeout){var $t=this;$t._timeout=setTimeout(function(){$t._hide(which)},timeout);}},_hide:function(which){this._elts[which].width(80);this._elts[which+'T'].width(0).hide();this._elts[which+'L'].animate({opacity:'0.3'},50).removeClass("hover").css({backgroundColor:"none"});}};ccmb.modules.navarticles.init();
(function($)
{$.warningCNIL.defaultOptions.excludePaths=[];$.warningCNIL.defaultOptions.setCookieOnDomain='!/ccm\.net/.test(document.location.toString())';$.warningCNIL.defaultOptions.getMoreURL=function()
{return'http://ccm.net/contents/957-processing-of-personal-data-ccm';};var domain=$.jet.env.packager.host==='/'?'astatic.ccmbg.com':$.jet.env.packager.host.split(/:\/\//)[1].split(/\//)[0];$.warningCNIL.defaultOptions.img.src=location.protocol+'//'+domain+'/www.commentcamarche.net/_skin/assets/img/logo_ccm_rouge.png';$.warningCNIL.defaultOptions.img.alt='CCM';}(jQuery));
(function($){if(typeof $data=='undefined')
$data={};if(typeof $data.ckeditor!=="undefined"&&$data.ckeditor.start===true){$('.ccmCkeditor').addCkeditor($data.ckeditor.getOptions()).then(function($node){$data.ckeditor.afterRender();}).catch(function(error){});}
$.jet.services.appSlider={start:false,options:{selector:'#slider',continuous:true,auto:($ccmprms&&$ccmprms.slider)?$ccmprms.slider.auto:true,pause:5000},init:function(){$(this.options.selector).sudoSlider(this.options);$(document).trigger('appSliderReady');}};$.jet.services.appTextArea={start:false,options:{$node:null,selector:'.textarea',getSelection:function($node){var textComponent=$node.find('textarea')[0];var selectedText;if(document.selection!=undefined){textComponent.focus();var sel=document.selection.createRange();selectedText=sel.text;}
else if(textComponent.selectionStart!=undefined){var startPos=textComponent.selectionStart;var endPos=textComponent.selectionEnd;selectedText=textComponent.value.substring(startPos,endPos);}
return selectedText;},setSelection:function($node,text){var $text=$node.find('textarea');var value=$text.val();$text.val(value.substring(0,$text[0].selectionStart)+text+value.substring($text[0].selectionEnd));}},init:function(options){options=$.extend(true,{},this.options,options);if(!options.$node){options.$node=$(options.selector);}
return options.$node.each(function(){var $this=$(this);$this.find('ul>li>a').click(function(e){e.preventDefault();var tag=$(this).attr('acttype');if(!tag){if($(this).hasClass('magicLink')){var url=prompt('Adresse :','http://');if(url!=null&&url!=''&&url!='http://'){var select=options.getSelection($this);options.setSelection($this,'['+url+' '+select+']');}}}else{var select=options.getSelection($this);options.setSelection($this,'<'+tag+'>'+select+'</'+tag+'>');}});});}};$.jet.services.appCode={start:false,options:{selector:'pre.code',container:document,readOnly:true,gutter:true,skin:'skin_msvcpp',editor:{langages:['basic','c','cpp','csharp','php','js','css','html','sql','xml','delphi','java','perl','python','ruby','sh','tcl','asm'],enabled:false,selector:'.textarea a.code, .actionsMessage a.code'},getSelection:function($node){var textComponent=$node[0];var selectedText;if(document.selection!=undefined){textComponent.focus();var sel=document.selection.createRange();selectedText=sel.text;}
else if(textComponent.selectionStart!=undefined){var startPos=textComponent.selectionStart;var endPos=textComponent.selectionEnd;selectedText=textComponent.value.substring(startPos,endPos);}
return selectedText;},setSelection:function($text,text){var value=$text.val();var end=$text[0].selectionEnd;var start=$text[0].selectionStart;$text.val(value.substring(0,start)+text+value.substring(end)).focus();if($text[0].setSelectionRange)
$text[0].setSelectionRange(start+text.length,start+text.length);else if($text[0].createTextRange){var e=$text[0].createTextRange();e.collapse(true);e.moveEnd('character',end);e.moveStart('character',start);e.select();}}},execute:function(options){$(options.container).find(options.selector).each(function(){var $this=$(this);if(typeof $this.codeSnippet=='function'){$this.codeSnippet({toolbar:false,language:$this.attr('data-mode')?$this.attr('data-mode'):'none',gutter:$this.attr('data-gutter')?$this.attr('data-gutter')=='true':options.gutter}).addClass(options.skin).addClass('line-numbers');}});if(options.editor.enabled){$(options.editor.selector).each(function(){var $this=$(this);if($this.hasClass('jDropDown'))
return;$this.addClass('jDropDown');var $menu=$('<div>').addClass('dropdown').hide().attr('tabindex',0);for(var i in options.editor.langages){var lang=options.editor.langages[i];$menu.append($('<a href="#"/>').attr('data-lang',lang).text(lang).click(function(e){e.preventDefault();var lang=$(this).attr('data-lang');var $target=$this.parents('.textarea, .addComment').first().find('textarea#message, textarea#newc0');if($target.length===0){$target=$this.parents('form.formAddComment').first().find('fieldset .textarea textarea[name="message"]');}
if($target.length===0){return;}
options.setSelection($target,'<code '+lang+'>'+options.getSelection($target)+'</code>');$menu.hide();})).blur(function(e){setTimeout(function(){$menu.hide();},200);});}
$this.parent().append($('<span>').addClass('more').html('&#9660;').click(function(e){e.preventDefault();$menu.show().focus();})).append($menu);});}},init:function(){var options=this.options;$.jet.services.appCode.execute(options);$(document).bind('ajaxComplete',function(){setTimeout(function(){$.jet.services.appCode.execute(options);},100);}).trigger('appCode');}};var setCookieDomain=true;if(/http:\/\/[^\/]*commentcamarche\.net/.test(document.location.toString())){setCookieDomain=false;}
$(document).start(function(){if(typeof $.fn.stick!=='undefined')
{$('.jSticker').stick();}});$(document).ready(function(){try{var sudoSlider=$("#slider").sudoSlider({continuous:true,auto:($ccmprms&&$ccmprms.slider)?$ccmprms.slider.auto:true,pause:5000});}catch(e){}}).trigger('start',[$.extend(true,{},{services:{tipsy:{start:false},fancybox:_$('$data.services')._.fancybox,appSlider:{start:false},goTop:{start:false},inRead:{start:true},inputDefault:{start:false},warningCNIL:{start:_$('$data.services.warningCNIL')._.start,options:{setCookieOnDomain:setCookieDomain}},cabestanRetargeting:{start:true},videoOnScroll:{options:{forceStart:window.document.URL.match(/#.*?ID=([-a-z0-9\.]+).*?&module=([a-z]+)/)!=null}}}},$data)]);}(jQuery));